<img align="left" style="padding-right:10px;" src="figuras/banner_cd.png">

# Proyecto de Machine Learning

## Descripción de los datos

In [1]:
# Importar librerias
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np

## 1. Obtención y visualización de los datos

In [2]:
df = pd.read_csv('datos/Datos_Train-Validation.csv')
df

,id,CustomerId,Surname,CreditScore,Gender-0Male-1Female,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,15674932,Okwudilichukwu,668,0,33,3,0.00,2,1,0,181449.97,0
1,1,15749177,Okwudiliolisa,627,0,33,1,0.00,2,1,1,49503.50,0
2,2,15694510,Hsueh,678,0,40,10,0.00,2,1,0,184866.69,0
3,3,15741417,Kao,581,0,34,2,148882.54,1,1,1,84560.88,0
4,4,15766172,Chiemenam,716,0,33,5,0.00,2,1,1,15068.83,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,15773776,K?,691,0,30,7,0.00,1,1,0,149991.32,0
9996,9996,15674720,Smith,667,1,37,7,123067.63,1,0,1,98162.44,0
9997,9997,15757628,Hsieh,791,0,35,4,80793.58,1,1,0,28188.96,0
9998,9998,15662404,Nwachinemelu,619,0,46,4,0.00,2,1,0,149991.71,0
9999,9999,15806901,Tien,671,0,32,7,0.00,1,1,1,90876.95,0

## 2. Preparación de los datos y funciones

In [3]:
# Preparación de datos
from sklearn.model_selection import train_test_split

#### División general de los datos


* **X**: Datos sin el diagnostico es decir sin la columna "target"
* **y**: Datos con el diagnostico es decir con la columna "target"

Muestras de entrenamiento y prueba
* **X_train**: este será el grupo de entrenamiento
* **X_test**: este será el  grupo de prueba
* **y_train**: este será el target para el grupo de entrenamiento
* **y_test**: este será el target para el grupo de prueba

In [4]:
#Crear X (Quitar la columna o campo 24)
X =df.drop(['id','CustomerId','Surname','Exited'], axis=1)
X.head(2)

,CreditScore,Gender-0Male-1Female,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,668,0,33,3,0.0,2,1,0,181449.97
1,627,0,33,1,0.0,2,1,1,49503.50

In [5]:
# Crear y (Valor de de la columna "target")
y=df['Exited']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Exited, dtype: int64

In [6]:
X

,CreditScore,Gender-0Male-1Female,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,668,0,33,3,0.00,2,1,0,181449.97
1,627,0,33,1,0.00,2,1,1,49503.50
2,678,0,40,10,0.00,2,1,0,184866.69
3,581,0,34,2,148882.54,1,1,1,84560.88
4,716,0,33,5,0.00,2,1,1,15068.83
...,...,...,...,...,...,...,...,...,...
9995,691,0,30,7,0.00,1,1,0,149991.32
9996,667,1,37,7,123067.63,1,0,1,98162.44
9997,791,0,35,4,80793.58,1,1,0,28188.96
9998,619,0,46,4,0.00,2,1,0,149991.71
9999,671,0,32,7,0.00,1,1,1,90876.95

In [7]:
# Dividir los datos para entrenamiento y prueba. Con un factor 80%
X_train , X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)
print( 'X_train :' , X_train.shape )
print( 'X_test :' , X_test.shape )
print( 'y_train :' , y_train.shape )
print( 'y_test :' ,  y_test.shape )
print( 'df 100% :' ,  df.shape[0]   )
print( 'df 80% :' ,  df.shape[0] * 0.8 )

X_train : (8000, 9)
X_test : (2000, 9)
y_train : (8000,)
y_test : (2000,)
df 100% : 10000
df 80% : 8000.0

### Pipeline

<img src="figuras/pipeline.jpg" align="middle" style="width:400px;" />

In [8]:
# Modulos importantes
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [9]:
# Mostrando columnas
X.columns

Index(['CreditScore', 'Gender-0Male-1Female', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [10]:
# Crear la lista de  viriables numericas  numeric_list 
numeric_list = ['CreditScore', 'Gender-0Male-1Female', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']

In [11]:
# Crear el pipeline de preprocesamiento para datos numéricos  numeric_transformer
numeric_transformer = Pipeline(  steps = [ ('scaler',  StandardScaler()  )  ]   )

In [12]:
# Definir los transformadores
transformer = ColumnTransformer( [ ('num', numeric_transformer, numeric_list  )  ]  )

# 3. Implementación de Modelos

## Segundo modelo: Multi Layer Perceptron (MLP)

Referencia
* https://michael-fuchs-python.netlify.app/2021/02/03/nn-multi-layer-perceptron-classifier-mlpclassifier/

## a) MLP sin tunning

In [13]:
# Módulos del Modelo
from sklearn.neural_network import MLPClassifier

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [14]:
# modelo DecisionTreeClassifier llamado DT_Classifier
MLP_Classifier = MLPClassifier(max_iter = 1000)

In [15]:
# Parametros del modelo DecisionTreeClassifier()
MLP_Classifier.get_params()

{'activation': 'relu',
 'alpha': 0.0001,
 'batch_size': 'auto',
 'beta_1': 0.9,
 'beta_2': 0.999,
 'early_stopping': False,
 'epsilon': 1e-08,
 'hidden_layer_sizes': (100,),
 'learning_rate': 'constant',
 'learning_rate_init': 0.001,
 'max_fun': 15000,
 'max_iter': 1000,
 'momentum': 0.9,
 'n_iter_no_change': 10,
 'nesterovs_momentum': True,
 'power_t': 0.5,
 'random_state': None,
 'shuffle': True,
 'solver': 'adam',
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': False,
 'warm_start': False}

In [16]:
# Definiendo el modelo_DT con su pipeline
modelo_MLP = Pipeline(  [ ('transformer', transformer) , 
                        ('MLP_Classifier',MLP_Classifier)    ]  )

In [17]:
# Ajuste del modelo
modelo_MLP.fit(X_train, y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['CreditScore',
                                                   'Gender-0Male-1Female',
                                                   'Age', 'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary'])])),
                ('MLP_Classifier', MLPClassifier(max_iter=1000))])

In [18]:
# Score sin tunning
modelo_MLP.score(X_test, y_test)

0.8455

## b) MLP con tunning

In [19]:
# Definir los parametros con el diccionario params utilizando:
hidden_layer_sizes= [(150,100,50), (120,80,40), (100,50,30)]
max_iter= [ 500 ]
activation= ['tanh', 'relu']
solver= ['sgd']
alpha= [0.0001, 0.05]

params = { 'MLP_Classifier__hidden_layer_sizes' : hidden_layer_sizes,
         'MLP_Classifier__max_iter': max_iter,
         'MLP_Classifier__activation': activation ,
         'MLP_Classifier__solver': solver ,
         'MLP_Classifier__alpha': alpha }

In [20]:
# Ajuste de los parametros max_depth y min_samples_leaf con  GridSearchCV
from sklearn.model_selection import GridSearchCV

grid_MLP = GridSearchCV(modelo_MLP, 
                       param_grid= params,
                      cv=5,
                      scoring='neg_mean_squared_error',
                      n_jobs=-1,
                      verbose=10)

In [21]:
# Ajuste del modelo usando todas las posibles combinaciones de parametros 
grid_MLP.fit(X, y)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5; 1/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 5/5; 1/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 2/5; 1/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 3/5; 1/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 4/5; 1/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 2/5; 2/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 3/5; 2/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 1/5; 2/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 1/5; 2/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time=  36.2s
[CV 4/5; 2/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 2/5; 2/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.147 total time=  37.8s
[CV 5/5; 2/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 5/5; 1/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time=  38.5s
[CV 1/5; 3/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 3/5; 2/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.147 total time=  38.9s
[CV 2/5; 3/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 4/5; 1/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.142 total time=  40.4s
[CV 3/5; 3/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 1/5; 1/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.147 total time=  44.9s
[CV 4/5; 3/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 3/5; 1/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.145 total time=  50.4s
[CV 5/5; 3/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 2/5; 1/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.144 total time=  57.4s
[CV 1/5; 4/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 1/5; 3/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.147 total time=  23.9s
[CV 2/5; 4/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 3/5; 3/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.144 total time=  24.4s
[CV 3/5; 4/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 2/5; 3/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.146 total time=  29.6s
[CV 4/5; 4/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 5/5; 3/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time=  20.9s
[CV 5/5; 4/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 4/5; 2/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.145 total time=  35.1s
[CV 1/5; 5/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 4/5; 3/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.148 total time=  27.9s
[CV 2/5; 5/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 5/5; 2/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.152 total time=  37.9s
[CV 3/5; 5/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 1/5; 4/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time=  47.9s
[CV 4/5; 5/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 1/5; 5/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.147 total time=  33.8s
[CV 5/5; 5/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 2/5; 4/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.146 total time=  44.4s
[CV 1/5; 6/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 2/5; 5/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.145 total time=  36.8s
[CV 2/5; 6/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 3/5; 4/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.144 total time=  46.5s
[CV 3/5; 6/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 5/5; 4/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.151 total time=  40.2s
[CV 4/5; 6/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 3/5; 5/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.145 total time=  39.2s
[CV 5/5; 6/12] START MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 4/5; 4/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.145 total time=  46.4s
[CV 1/5; 7/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 4/5; 5/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.144 total time=  25.3s
[CV 2/5; 7/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 1/5; 6/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.147 total time=  25.6s
[CV 3/5; 7/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 2/5; 6/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time=  25.0s
[CV 4/5; 7/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 4/5; 6/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.145 total time=  24.7s
[CV 5/5; 7/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 5/5; 5/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.151 total time=  32.3s
[CV 1/5; 8/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 3/5; 6/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.144 total time=  28.0s
[CV 2/5; 8/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 5/5; 6/12] END MLP_Classifier__activation=tanh, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.149 total time=  26.9s
[CV 3/5; 8/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 1/5; 8/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.152 total time= 1.2min
[CV 4/5; 8/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 1/5; 7/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.155 total time= 1.6min
[CV 5/5; 8/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 2/5; 8/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time= 1.2min
[CV 1/5; 9/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 3/5; 8/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time= 1.1min
[CV 2/5; 9/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 2/5; 7/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time= 1.5min
[CV 3/5; 9/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 3/5; 7/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.152 total time= 1.5min
[CV 4/5; 9/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 4/5; 7/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.143 total time= 1.5min
[CV 5/5; 9/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 5/5; 7/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.153 total time= 1.5min
[CV 1/5; 10/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 1/5; 9/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.151 total time=  47.1s
[CV 2/5; 10/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 3/5; 9/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.151 total time=  36.2s
[CV 3/5; 10/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 2/5; 9/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.148 total time=  47.3s
[CV 4/5; 10/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 4/5; 9/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.146 total time=  45.6s
[CV 5/5; 10/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 4/5; 8/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.148 total time= 1.0min
[CV 1/5; 11/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 5/5; 8/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.154 total time= 1.1min
[CV 2/5; 11/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd
[CV 5/5; 9/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.0001, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.151 total time=  47.9s
[CV 3/5; 11/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 1/5; 10/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.151 total time= 1.4min
[CV 4/5; 11/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 1/5; 11/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.152 total time= 1.1min
[CV 5/5; 11/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 2/5; 11/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time= 1.1min
[CV 1/5; 12/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 3/5; 11/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.145 total time= 1.1min
[CV 2/5; 12/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 2/5; 10/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.152 total time= 1.5min
[CV 3/5; 12/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 4/5; 10/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.151 total time= 1.5min
[CV 4/5; 12/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 3/5; 10/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.148 total time= 1.5min
[CV 5/5; 12/12] START MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 5/5; 10/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(150, 100, 50), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.152 total time= 1.4min

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 4/5; 11/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.151 total time= 1.0min

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 2/5; 12/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.156 total time=  34.8s

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 1/5; 12/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time=  41.3s
[CV 4/5; 12/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.149 total time=  34.6s
[CV 3/5; 12/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.148 total time=  37.2s

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 5/5; 12/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(100, 50, 30), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.150 total time=  36.2s

/home/yosake/.pyenv/versions/3.10.11/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

[CV 5/5; 11/12] END MLP_Classifier__activation=relu, MLP_Classifier__alpha=0.05, MLP_Classifier__hidden_layer_sizes=(120, 80, 40), MLP_Classifier__max_iter=500, MLP_Classifier__solver=sgd;, score=-0.151 total time=  49.0s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('transformer',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('scaler',
                                                                                          StandardScaler())]),
                                                                         ['CreditScore',
                                                                          'Gender-0Male-1Female',
                                                                          'Age',
                                                                          'Tenure',
                                                                          'Balance',
                                                                          'NumOfProducts',
                                                                          'HasCrCard',
                                                                          'IsActiveMember',
                                                                          'EstimatedSalary'])])),
                                       ('MLP_Classifier',
                                        MLPClassifier(max_iter=1000))]),
             n_jobs=-1,
             param_grid={'MLP_Classifier__activation': ['tanh', 'relu'],
                         'MLP_Classifier__alpha': [0.0001, 0.05],
                         'MLP_Classifier__hidden_layer_sizes': [(150, 100, 50),
                                                                (120, 80, 40),
                                                                (100, 50, 30)],
                         'MLP_Classifier__max_iter': [500],
                         'MLP_Classifier__solver': ['sgd']},
             scoring='neg_mean_squared_error', verbose=10)

In [27]:
#Encontrar los mejores parametros con best_params_
grid_MLP.best_params_

{'MLP_Classifier__activation': 'tanh',
 'MLP_Classifier__alpha': 0.0001,
 'MLP_Classifier__hidden_layer_sizes': (150, 100, 50),
 'MLP_Classifier__max_iter': 500,
 'MLP_Classifier__solver': 'sgd'}

In [28]:
# Ajustar el modelo con los nuevos parametros nombrandolo como  DT_Classifier_tunned
MLP_Classifier_tunned =  MLPClassifier(activation='tanh',
                                              alpha=0.0001 , 
                                                hidden_layer_sizes=(150, 100, 50),
                                               max_iter=500,
                                               solver='sgd')

In [29]:
# Definiendo el modelo_DT con su pipeline
modelo_MLP_tunned = Pipeline(  [ ('transformer', transformer) , 
                        ('MLP_Classifier_tunned',MLP_Classifier_tunned)    ]  )

In [30]:
#  Ajustar el modelo
modelo_MLP_tunned.fit(X_train, y_train)

Pipeline(steps=[('transformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['CreditScore',
                                                   'Gender-0Male-1Female',
                                                   'Age', 'Tenure', 'Balance',
                                                   'NumOfProducts', 'HasCrCard',
                                                   'IsActiveMember',
                                                   'EstimatedSalary'])])),
                ('MLP_Classifier_tunned',
                 MLPClassifier(activation='tanh',
                               hidden_layer_sizes=(150, 100, 50), max_iter=500,
                               solver='sgd'))])

In [31]:
# Predicción
y_predict = modelo_MLP_tunned.predict(X_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [32]:
# Prueba en y_test
y_test.values

array([0, 0, 0, ..., 0, 1, 1], shape=(2000,))

In [33]:
# Comparación
#np.equal(  y_predict , y_test.values )

In [34]:
# Score
np.equal(  y_predict , y_test.values ).sum() / len(y_predict)

np.float64(0.852)

In [35]:
# Score
modelo_MLP_tunned.score(X_test, y_test)

0.852

In [36]:
#Evaluacion
# Calcular el score con la validación cruzada CV=5
from sklearn.model_selection import cross_val_score

MLP_tunned_scores= cross_val_score( modelo_MLP_tunned, X, y,
                              scoring= 'neg_mean_squared_error', cv=5)
MLP_tunned_scores

array([-0.1515, -0.1475, -0.1445, -0.1445, -0.148 ])

In [37]:
# Realizar el cambio de signo y sacar la raiz
MLP_tunned_rmse_scores= np.sqrt(-MLP_tunned_scores)
MLP_tunned_rmse_scores

array([0.38923001, 0.38405729, 0.38013156, 0.38013156, 0.38470768])

In [38]:
#Calcular mean y standard deviation
media_MLP_tunned= MLP_tunned_rmse_scores.mean() 
std_MLP_tunned=MLP_tunned_rmse_scores.std()
print( media_MLP_tunned)
print( std_MLP_tunned)

0.38365161801947145
0.0033817142164286654

| Modelo o clasificador   | Score |  Mean | Standard deviation  |  Parámetros de ajuste  |
|---|---|---|---|---|
|   MLP | 0.0  |     |        |    |
|   MLP  Tunned| 0.0   |  0.0  |   0.0    |   max_depth: 0,  min_samples_leaf: 0   |

### Guardar el modelo entrenado

In [39]:
import joblib

In [40]:
#Exportar el modelo
#joblib.dump(modelo, 'Ubicación del archivo .joblib')
joblib.dump(modelo_MLP_tunned, 'modelos/modelo_MLP_tunned.joblib')

['modelos/modelo_MLP_tunned.joblib']