<!--Información del curso-->
<img align="left" style="padding-right:10px;" src="figuras/logo_ciencia_datos.png">

<center><h1 style="font-size:2em;color:#2467C0"> Ejercicio  </h1></center>

<center><h2 style="font-size:2em;color:#840700">  Incendios en México </h4></center>

<br>
<table>
<col width="550">
<col width="450">
<tr>
<td><img src="figuras/incendio.jpg" align="left" style="width:500px"/></td>
<td>

* **La Comisión Nacional Forestal (CONAFOR)** es la institución federal encargada de operar, desde septiembre de 2002, el Programa Nacional de Protección contra Incendios Forestales en México, cuyo objetivo es proteger los recursos forestales de la presencia de incendios y atacar las causas que los originan. Para ello despliega acciones específicas en materia de prevención, detección, control y combate. 

* **¿Qué es un incendio forestal?** Un incendio forestal es la propagación libre y no programada del fuego sobre la vegetación en los bosques selvas y zonas áridas y semiáridas. 

* Se calcula que **las actividades humanas ocasionan el 99%** de éstos incendios y sólo el resto tiene como causa fenómenos naturales 
    
<br>
</td>
</tr>
</table>

# Librerías

Cargando las bibliotecas que necesitamos

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
# cargar el archivo datos/Serie_historica_anual_incendios_2017.csv en un dataframe llamado df
df_incendios = pd.read_csv("datos/Serie_historica_anual_incendios_2017.csv")

<div class="alert alert-info">

<b>EJERCICIO</b>:

 <ul>
  <li>Muestre el número total de filas y columnas </li>
</ul>
</div>

In [11]:
#Numero total de filas y columnas
df_incendios.shape

(8872, 37)

<div class="alert alert-info">

<b>EJERCICIO</b>:

 <ul>
  <li>Muestre los nombres de las columnas </li>
</ul>
</div>

In [12]:
#Columnas
df_incendios.columns

Index(['Número de Incendio', 'Clave del incendio', 'Grados', 'Minutos',
       'Segundos', 'Grados.1', 'Minutos.1', 'Segundos.1', 'Clave municipio',
       'Estado', 'Municipio', 'Predio', 'Causa', 'Fecha Inicio',
       'Fecha Termino', 'Mes Acontecimiento', 'Duración días',
       'Tipo de incendio', 'Tipo Vegetacion', 'Tipo Impacto',
       'Arbolado Adulto', 'Renuevo', 'Arbustivo', 'Herbaceo', 'Hojarasca',
       'Suelo Organico', 'Total Hectareas', 'Tamaño', 'Deteccion', 'Llegada',
       'Duracion HMS', 'Duracion H', 'Costos MXN', 'Superficie Salvada',
       'CO2 emitido', 'CO2 Evito emitir', 'Region'],
      dtype='object')

Columnas importantes:
* Estado: Entidad Federativa
* Municipio: Municipio
* Tipo Impacto: Tipo impacto del incendio
* Causa: Causa del incendio
* Mes Acontecimiento: Mes en el que ocurrió el incendio
* Total Hectareas: Total de suelo afectado en Hectáreas 
* Duracion HMS: Duración en Hora:Minutos:Segundos
* Duracion H-Decimal: Duración en horas decimales

<div class="alert alert-info">

<b>EJERCICIO</b>:

 <ul>
  <li>Muestre el tipo de dato de cada columna </li>
</ul>
</div>

In [13]:
#tipos de variables
df_incendios.dtypes

Número de Incendio      int64
Clave del incendio     object
Grados                 object
Minutos                 int64
Segundos              float64
Grados.1                int64
Minutos.1               int64
Segundos.1            float64
Clave municipio         int64
Estado                 object
Municipio              object
Predio                 object
Causa                  object
Fecha Inicio           object
Fecha Termino          object
Mes Acontecimiento     object
Duración días          object
Tipo de incendio       object
Tipo Vegetacion        object
Tipo Impacto           object
Arbolado Adulto         int64
Renuevo                 int64
Arbustivo               int64
Herbaceo                int64
Hojarasca               int64
Suelo Organico          int64
Total Hectareas         int64
Tamaño                 object
Deteccion              object
Llegada                object
Duracion HMS           object
Duracion H            float64
Costos MXN            float64
Superficie Salvada    float64
CO2 emitido           float64
CO2 Evito emitir      float64
Region                 object
dtype: object

<div class="alert alert-info">

<b>EJERCICIO</b>:

 <ul>
  <li>Muestre los principales características estadísticas de parámetro cuantitativo  </li>
</ul>
</div>

In [14]:
#
df_incendios.describe()

,Número de Incendio,Minutos,Segundos,Grados.1,Minutos.1,Segundos.1,Clave municipio,Arbolado Adulto,Renuevo,Arbustivo,Herbaceo,Hojarasca,Suelo Organico,Total Hectareas,Duracion H,Costos MXN,Superficie Salvada,CO2 emitido,CO2 Evito emitir
count,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8872.000000,8.872000e+03,8872.000000,8.872000e+03,8.872000e+03
mean,321.784378,26.552750,29.518481,99.877480,27.684851,29.526105,54.905207,2.432372,1.665577,21.021190,32.638413,23.082732,0.595469,81.409829,6.204995,1.712718e+04,1239.907328,2.982856e+03,4.680880e+04
std,310.332721,17.943577,17.330145,9.732331,17.690869,17.477507,67.260830,44.084256,16.747957,203.451119,331.118147,190.777683,11.336051,613.414613,6.292960,1.056273e+05,9349.790127,2.631238e+04,4.128974e+05
min,1.000000,0.000000,0.000000,-101.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.100000e+01,0.150000,0.000000e+00,0.000000e+00
25%,84.000000,10.000000,14.500000,98.000000,12.000000,14.400000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.250000,2.684050e+03,22.860000,5.324000e+01,8.181300e+02
50%,223.000000,25.000000,29.170000,99.000000,27.000000,29.200000,32.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,5.000000,4.000000,4.533445e+03,70.110000,1.681800e+02,2.640025e+03
75%,470.000000,42.000000,44.500000,103.000000,43.000000,44.700000,80.000000,0.000000,0.000000,5.000000,6.000000,2.000000,0.000000,23.000000,7.602500,8.800000e+03,350.570000,8.031575e+02,1.270823e+04
max,1450.000000,59.000000,60.000000,117.000000,59.000000,83.000000,570.000000,3000.000000,755.000000,12755.000000,14000.000000,7069.000000,650.000000,21538.000000,220.000000,3.785356e+06,328282.200000,1.705756e+06,2.634777e+07

<div class="alert alert-success">
    
1. a) Encontrar el Total de Hectareas afectadas por estado. b) Encontrar el Total de Hectareas afectadas por estado, ordenando los datos de mayor a menor
    
</div>

In [15]:
# a) Encontrar el Total de Hectareas afectadas por estado.
pd.DataFrame(df_incendios.groupby('Estado')['Total Hectareas'].sum())

                     Total Hectareas
Estado
Aguascalientes                  4734
Baja California                50957
Baja California Sur               77
Campeche                       13822
Chiapas                        13021
Chihuahua                      87285
Ciudad de México                2367
Coahuila                       10303
Colima                          2031
Durango                        40323
Guanajuato                      7665
Guerrero                       24079
Hidalgo                         2978
Jalisco                       189816
Michoacán                      14452
Morelos                         3422
México                         11932
Nayarit                        32299
Nuevo León                       733
Oaxaca                         41718
Puebla                         10571
Querétaro                       2556
Quintana Roo                    9628
San Luis Potosí                 4383
Sinaloa                         3354
Sonora                        101072
Tabasco                          989
Tamaulipas                      2670
Tlaxcala                        2452
Veracruz                        3258
Yucatán                        11012
Zacatecas                      16309

In [16]:
# b) Encontrar el Total de Hectareas afectadas por estado, ordenando los datos de mayor a menor
pd.DataFrame(df_incendios.groupby('Estado')['Total Hectareas'].sum().sort_values(ascending=False))

                     Total Hectareas
Estado
Jalisco                       189816
Sonora                        101072
Chihuahua                      87285
Baja California                50957
Oaxaca                         41718
Durango                        40323
Nayarit                        32299
Guerrero                       24079
Zacatecas                      16309
Michoacán                      14452
Campeche                       13822
Chiapas                        13021
México                         11932
Yucatán                        11012
Puebla                         10571
Coahuila                       10303
Quintana Roo                    9628
Guanajuato                      7665
Aguascalientes                  4734
San Luis Potosí                 4383
Morelos                         3422
Sinaloa                         3354
Veracruz                        3258
Hidalgo                         2978
Tamaulipas                      2670
Querétaro                       2556
Tlaxcala                        2452
Ciudad de México                2367
Colima                          2031
Tabasco                          989
Nuevo León                       733
Baja California Sur               77

<div class="alert alert-success">
    
2. Encontrar el tiempo promedio de los incendios por estado, ordenando los datos de mayor a menor
    
</div>

In [17]:
pd.DataFrame(df_incendios.groupby('Estado')['Duracion H'].mean().sort_values(ascending=False))

                     Duracion H
Estado
Tamaulipas            11.441176
Sinaloa               11.405870
Sonora                11.177286
Chiapas               10.777897
Nayarit               10.327909
Oaxaca                 9.135556
Guanajuato             8.970185
Tabasco                8.933500
Guerrero               8.809113
Jalisco                8.664519
San Luis Potosí        8.568452
Durango                8.498481
Quintana Roo           8.468750
Nuevo León             8.028298
Campeche               7.896552
Zacatecas              7.497907
Coahuila               7.068377
Colima                 7.063452
Querétaro              6.407778
Aguascalientes         6.359241
Michoacán              6.262907
Veracruz               6.253992
Yucatán                6.250000
Chihuahua              6.187698
Puebla                 5.942788
Baja California        5.672073
Hidalgo                4.665182
Morelos                4.315219
Baja California Sur    3.868571
Ciudad de México       3.497871
México                 3.189738
Tlaxcala               3.097314

<div class="alert alert-success">
    
3. ¿Cuáles son los diferentes tipos de causas de incendios según los datos?
    
</div>

In [18]:
df_incendios.sort_values('Causa')['Causa'].unique().tolist()

['ACTIVIDADES \nAGROPECUARIAS',
 'ACTIVIDADES AGROPECUARIAS',
 'CAZADORES',
 'FESTIVIDADES Y RITUALES',
 'FOGATAS',
 'FOGATAS ',
 'FUMADORES',
 'INTENCIONAL',
 'LIMPIAS DE DERECHO DE VÍA',
 'NATURALES',
 'OTRAS ACTIVIDADES PRODUCTIVAS',
 'OTRAS CAUSAS',
 'QUEMA DE BASUREROS',
 'RESIDUOS DE APROVECHAMIENTO FORESTAL',
 'TRANSPORTES']

<div class="alert alert-success">
    
4. ¿Cuál es el total de Hectáreas afectadas según las causas de los incendios? Ordenar los datos de mayor a menor

    
</div>

In [19]:
pd.DataFrame(df_incendios.groupby('Causa')['Total Hectareas'].sum().sort_values(ascending=False))

                                      Total Hectareas
Causa
OTRAS CAUSAS                                   214272
ACTIVIDADES AGROPECUARIAS                      201373
INTENCIONAL                                     85343
NATURALES                                       79308
FUMADORES                                       46786
FOGATAS                                         36452
CAZADORES                                       21384
QUEMA DE BASUREROS                              17302
LIMPIAS DE DERECHO DE VÍA                       11168
OTRAS ACTIVIDADES PRODUCTIVAS                    7669
RESIDUOS DE APROVECHAMIENTO FORESTAL              747
TRANSPORTES                                       294
FESTIVIDADES Y RITUALES                           157
ACTIVIDADES \nAGROPECUARIAS                        11
FOGATAS                                             2

<div class="alert alert-success">
    
5. ¿Cuáles son los diferentes tipos de impactos según los datos?
    
</div>

In [20]:
df_incendios.sort_values('Tipo Impacto')['Tipo Impacto'].unique().tolist()

['IMPACTO MODERADO', 'IMPACTO MÍNIMO', 'IMPACTO SEVERO']

<div class="alert alert-success">
    
6. ¿Cuáles es el total de costos por cada tipo de impacto ?
    
</div>

In [21]:
pd.DataFrame(df_incendios.groupby('Tipo Impacto')['Costos MXN'].sum().sort_values(ascending=False))

                    Costos MXN
Tipo Impacto
IMPACTO MÍNIMO    1.057902e+08
IMPACTO MODERADO  3.820436e+07
IMPACTO SEVERO    7.957767e+06

<div class="alert alert-success">
    
7. Muestre los 10 estados con mayor superficie afectada (Total Hectareas). ¿En que lugar esta Yucatán?
    
</div>

In [22]:
pd.DataFrame(df_incendios.groupby('Estado')['Total Hectareas'].sum().sort_values(ascending=False)).head(10).reset_index()

            Estado  Total Hectareas
0          Jalisco           189816
1           Sonora           101072
2        Chihuahua            87285
3  Baja California            50957
4           Oaxaca            41718
5          Durango            40323
6          Nayarit            32299
7         Guerrero            24079
8        Zacatecas            16309
9        Michoacán            14452

In [23]:
pd.DataFrame(df_incendios.groupby('Estado')['Total Hectareas'].sum().sort_values(ascending=False)).head(14).reset_index()

             Estado  Total Hectareas
0           Jalisco           189816
1            Sonora           101072
2         Chihuahua            87285
3   Baja California            50957
4            Oaxaca            41718
5           Durango            40323
6           Nayarit            32299
7          Guerrero            24079
8         Zacatecas            16309
9         Michoacán            14452
10         Campeche            13822
11          Chiapas            13021
12           México            11932
13          Yucatán            11012

<div class="alert alert-success">
    
8. Definir un nuevo *DataFrame* llamado df_yucatan el cual solo tenga datos de Yucatan.  Muestre la efectación total de superficie (Total Hectareas) en los diferentes municipios en Yucatán
    
</div>

In [24]:
df_yucatan = pd.DataFrame(df_incendios[df_incendios['Estado'] == 'Yucatán'])

In [25]:
pd.DataFrame(df_yucatan.groupby('Municipio')['Total Hectareas'].sum())

                 Total Hectareas
Municipio
Abalá                        308
Cacalchén                    900
Calotmul                      60
Celestún                       2
Chemax                        94
Dzilam de Bravo              904
Hunucmá                     1643
Izamal                       331
Mocochá                      110
Motul                         87
Oxkutzcab                     20
Río Lagartos                1304
Sacalum                      243
TEKAX                          3
Tekax                        628
Tekit                        575
Temozón                       23
Tetiz                         35
Tixkokob                    1031
Tizimín                     1654
Tzucacab                     611
Valladolid                    63
Yaxcabá                      383

<div class="alert alert-success">
    
9. Utilizando *DataFrame* "df_yucatan", muestre la afectación total de superficie en los diferentes meses (Mes Acontecimiento) ordenado de Mayor a menor. ¿Cuál es el mes más propenso a los incendios?
    
</div>

In [26]:
df_mes = pd.DataFrame(df_yucatan.groupby('Mes Acontecimiento')['Total Hectareas'].sum().sort_values(ascending=False))
df_mes

                    Total Hectareas
Mes Acontecimiento
marzo                          4324
mayo                           1943
agosto                         1928
febrero                        1566
abril                           975
enero                           276

In [27]:
print("Mes mas propenso a incendios en Yucatan: ", df_mes.index[0])

Mes mas propenso a incendios en Yucatan:  marzo

<div class="alert alert-success">
    
10. Utilizando el *DataFrame* "df_yucatan", muestre los costos de los incendios en los diferentes municipios en Yucatán
    
</div> 
    
</div>

In [28]:
pd.DataFrame(df_yucatan.groupby('Municipio')['Costos MXN'].sum())

                 Costos MXN
Municipio
Abalá              184965.0
Cacalchén          744736.0
Calotmul           106200.0
Celestún             2300.0
Chemax              62510.0
Dzilam de Bravo    384021.0
Hunucmá           1216936.0
Izamal              37260.0
Mocochá             73432.0
Motul               52540.0
Oxkutzcab           70130.0
Río Lagartos        76520.0
Sacalum            177590.0
TEKAX               12595.0
Tekax              292368.0
Tekit              199360.0
Temozón              7980.0
Tetiz               13200.0
Tixkokob           789645.0
Tizimín            405535.0
Tzucacab           234890.0
Valladolid          46820.0
Yaxcabá             22890.0